---
name: python-app-final-cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set up variables
        shell: bash
        run: |
          echo "commit_id=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/python-app-final:${{ env.commit_id }}
    outputs:
      commit_id: ${{ env.commit_id }}
  
  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Modify helm values file
        shell: bash
        run: |
          echo "Commit ID: ${{ needs.ci.outputs.commit_id }}"
          sudo apt update && sudo apt install -y yq
          yq -Yi '.image.tag = "${{needs.ci.outputs.commit_id}}"' charts/python-app-final/values-dev.yaml

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Updated image tag to ${{ needs.ci.outputs.commit_id }}"
    
      - name: Install argocd cli
        shell: bash
        run: |
          curl -ksSL -o argocd-linux-amd64 https://argocd-server.argocd/download/argocd-linux-amd64
          sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd

      - name: ArgoCD login
        shell: bash
        run: |
          argocd login argocd-server.argocd \
            --insecure \
            --grpc-web \
            --username admin \
            --password ${{ secrets.ARGOCD_PASSWORD }}

      - name: ArgoCD create repo and app if not exists
        shell: bash
        run: |
          repo="https://github.com/lazrb-backstage/python-app-final"
          # create the repo
          argocd app list | grep -q $repo || argocd repo add $repo

          # create the app
          argocd app get python-app-final || argocd app create python-app-final \
            --repo $repo \
            --path charts/python-app-final \
            --dest-namespace dev \
            --dest-server https://kubernetes.default.svc \
            --values values-dev.yaml \
            --revision main \
            --sync-policy manual \
            --sync-option CreateNamespace=true

      - name: ArgoCD app sync
        shell: bash
        run: |
          argocd app sync python-app-final
          # wait for the app to be synced
          # argocd app wait python-app-final --timeout 180

